name: Build RTL8812BU OpenWrt Driver

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install tree build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget -y

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 -b openwrt-23.05 https://github.com/openwrt/openwrt.git
          cd openwrt
          echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add RTL8812BU package
        run: |
          cd openwrt/package/kernel
          git clone https://github.com/hkucs-makerlab/openwrt-rtl8812bu-package rtl88x2bu

      - name: Configure build
        run: |
          cd openwrt
          make defconfig
          ./scripts/feeds install rtl88x2bu

      - name: Build RTL8812BU driver package
        run: |
          cd openwrt
          make package/kernel/rtl88x2bu/compile V=s

      - name: Upload driver package artifact
        uses: actions/upload-artifact@v4
        with:
          name: rtl88x2bu-ipk
          path: openwrt/bin/packages/**/kmod-rtl88x2bu*.ipk
