name: Make OpenWRT x86 88x2bu image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Requirements
        run: |
          sudo apt update
          sudo apt install -y tree build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
          
      - name: Clone OpenWrt (faster from GitHub)
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout v24.10.2

      - name: Update & Install Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Clone 88x2bu-openwrt repo
        run: |
          cd openwrt
          git clone https://github.com/mirobiala/rtl88x2bu-cl package/kernel/rtl88x2bu-cl
          cd package/kernel/rtl88x2bu-cl
          git checkout v1.3.1

      - name: Dump Configs
        run: |
          cd openwrt
          curl -fsSL https://raw.githubusercontent.com/piratepope/rtl88x2bu-cl/refs/heads/main/config.txt -o .config

      - name: Generate kernel configs
        run: |
          cd openwrt
          make defconfig

      - name: Build OpenWrt toolchain
        run: |
          cd openwrt
          make toolchain/install V=s

      - name: Its Baking Time 
        run: |
          cd openwrt
          echo using $(nproc) cores
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: rtl88x2bu-ipk
          path: openwrt/bin/packages/x86_64/*/kmod-rtl88x2bu*.ipk
